// VIALBREAK Auto-Cracker automation. Unlocks at Containment 70.
const AUTO_TOOL_INDEX=()=>Number.isInteger(state.autoToolIndex)?state.autoToolIndex:8;
if(typeof state.autoCrack!=='boolean')state.autoCrack=false;
if(state.tool<AUTO_TOOL_INDEX())state.autoCrack=false;
let autoCrackTimer=null,autoAdvanceTimer=null,autoBulkTimer=null;
function autoRobotReady(){return state.tool>=AUTO_TOOL_INDEX()}
function autoEnabled(){return autoRobotReady()&&state.autoCrack===true}
function clearAutoTimers(){clearTimeout(autoCrackTimer);clearTimeout(autoAdvanceTimer);clearTimeout(autoBulkTimer);autoCrackTimer=autoAdvanceTimer=autoBulkTimer=null;$('#crackBtn')?.classList.remove('loading');$('#toolAnim')?.classList.remove('swing');$('#bulkCrackBtn')?.classList.remove('loading')}
function setAutoCrack(on){if(on&&!autoRobotReady()){toast('AUTO CRACK unlocks at Containment 70 with Auto-Cracker X.');return}state.autoCrack=!!on;save();syncAutoControls();if(!on){clearAutoTimers();toast('🤖 AUTO CRACK OFF');return}toast('🤖 AUTO CRACK ON');kickAutoNow()}
function autoButtonHTML(place){const locked=!autoRobotReady();return `<button class="auto-crack-toggle ${autoEnabled()?'on':''}" data-auto-crack="${place}" ${locked?'disabled':''}><span class="auto-dot"></span><b>${locked?'AUTO LOCKED':'AUTO CRACK'}</b><small>${locked?'Containment 70 • Auto-Cracker X':autoEnabled()?'ON • runs until switched off':'OFF • click to enable'}</small></button>`}
function mountOpeningAutoControl(){const s=$('#crackStation');if(!s||s.querySelector('[data-auto-crack="opening"]'))return;$('#crackBtn').insertAdjacentHTML('beforebegin',autoButtonHTML('opening'));bindAutoControls()}
function mountBulkAutoControl(){const b=$('#bulkCrackBtn');if(!b||$('#bulkOverlay .bulk-stage')?.querySelector('[data-auto-crack="bulk"]'))return;b.insertAdjacentHTML('beforebegin',autoButtonHTML('bulk'));bindAutoControls()}
function mountToolAutoControl(){const d=$('#currentToolDisplay');if(!d||d.querySelector('[data-auto-crack="tools"]'))return;d.insertAdjacentHTML('beforeend',autoButtonHTML('tools'));bindAutoControls()}
function bindAutoControls(){$$('[data-auto-crack]').forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound='1';btn.onclick=()=>setAutoCrack(!state.autoCrack)});syncAutoControls()}
function syncAutoControls(){$$('[data-auto-crack]').forEach(btn=>{const locked=!autoRobotReady();btn.disabled=locked;btn.classList.toggle('on',autoEnabled());const b=btn.querySelector('b'),s=btn.querySelector('small');if(b)b.textContent=locked?'AUTO LOCKED':'AUTO CRACK';if(s)s.textContent=locked?'Containment 70 • Auto-Cracker X':autoEnabled()?'ON • runs until switched off':'OFF • click to enable'})}
function runAutoCrack(){clearTimeout(autoCrackTimer);if(!autoEnabled())return;const o=$('#openingOverlay'),st=$('#crackStation'),b=$('#crackBtn');if(!o?.classList.contains('active')||!st||st.classList.contains('hidden')||!b||b.classList.contains('hidden'))return;b.classList.add('loading');$('#toolAnim')?.classList.add('swing');autoCrackTimer=setTimeout(()=>{if(!autoEnabled()){clearAutoTimers();return}b.classList.add('hidden');b.classList.remove('loading');$('#toolAnim')?.classList.remove('swing');beep(140,.07,'square',.04);setTimeout(()=>{if(autoEnabled())revealVial()},80)},Math.max(55,tool().time))}
function scheduleAutoCrack(delay=150){clearTimeout(autoCrackTimer);if(autoEnabled())autoCrackTimer=setTimeout(runAutoCrack,delay)}
function runAutoBulk(){clearTimeout(autoBulkTimer);if(!autoEnabled()||!bulkPending||bulkPending.committed)return;const b=$('#bulkCrackBtn');if(!b||b.classList.contains('hidden'))return;b.classList.add('loading');autoBulkTimer=setTimeout(()=>{if(!autoEnabled()||!bulkPending||bulkPending.committed){b.classList.remove('loading');return}b.classList.remove('loading');commitAndRevealBulk()},Math.max(120,tool().time*1.2))}
function kickAutoNow(){if(!autoEnabled())return;if($('#bulkOverlay')?.classList.contains('active')&&bulkPending&&!bulkPending.committed){runAutoBulk();return}scheduleAutoCrack(100)}
const autoBasePrepareSlot=prepareSlot;prepareSlot=function(){autoBasePrepareSlot();mountOpeningAutoControl();syncAutoControls();if(autoEnabled())scheduleAutoCrack(Math.max(90,tool().time*.45))};
const autoBaseRevealVial=revealVial;revealVial=function(){autoBaseRevealVial();if(!autoEnabled())return;clearTimeout(autoAdvanceTimer);const d=Math.max(180,Math.min(700,tool().time*1.5));if(slot<6)autoAdvanceTimer=setTimeout(()=>{if(!autoEnabled())return;slot++;$('#nextVialBtn').classList.add('hidden');$('#revealArea').classList.remove('active');setTimeout(()=>{if(!autoEnabled())return;prepareSlot();$('#crackStation').classList.remove('hidden')},60)},d);else autoAdvanceTimer=setTimeout(()=>{if(autoEnabled())finishRack()},Math.max(220,d))};
const autoBaseRenderTools=renderTools;renderTools=function(){autoBaseRenderTools();mountToolAutoControl();syncAutoControls()};
const autoBaseBuyTool=buyTool;buyTool=function(i){autoBaseBuyTool(i);if(autoRobotReady()){mountOpeningAutoControl();mountBulkAutoControl();mountToolAutoControl();syncAutoControls()}};
const autoBaseOpenBulkRackBatch=openBulkRackBatch;openBulkRackBatch=function(r,q){autoBaseOpenBulkRackBatch(r,q);mountBulkAutoControl();syncAutoControls();if(autoEnabled())autoBulkTimer=setTimeout(runAutoBulk,Math.max(120,tool().time*.8))};
const autoBaseFinishRack=finishRack;finishRack=function(){clearAutoTimers();autoBaseFinishRack();syncAutoControls()};
mountOpeningAutoControl();mountBulkAutoControl();renderAll();syncAutoControls();