const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],fmt=n=>Math.round(n).toLocaleString();
const rank={Stable:1,Oddity:2,Mutant:3,Hazard:4,'Black Label':5,Impossible:6};
const colors={Stable:'#a7c4b9',Oddity:'#73efa6',Mutant:'#62d7ff',Hazard:'#f4d85b','Black Label':'#ff6c85',Impossible:'#d67cff'};
const seed=[
['Sock Goblin Spore','Stable','🧦',22,'Makes every left sock disappear for exactly eleven minutes.','#72d88d','#1e824e'],['Mildly Suspicious Yogurt','Stable','🥛',18,'Technically alive. Emotionally unavailable.','#e9efb7','#a2a64f'],['Keyboard Fever','Stable','⌨',24,'Symptoms include typing “asdf” with unusual confidence.','#7fc4ff','#3466c4'],['Tuesday Flu','Stable','TUE',20,'Only active on Tuesdays. Researchers refuse to explain why.','#f6c55d','#a56d21'],['Dust Bunny Prime','Stable','☁',25,'Forms under laboratory furniture despite daily cleaning.','#d7dad4','#777d79'],['Snack Attack Strain','Stable','🍪',28,'Causes intense cravings whenever the vending machine is empty.','#e6a867','#a14b2b'],['Yawn-13','Stable','Zz',26,'One exposed technician reportedly slept through a fire drill.','#84aaff','#4854a9'],
['Disco Mold','Oddity','✦',58,'Glows only when nobody is looking directly at it.','#ff78d1','#6632ad'],['Quantum Sneeze','Oddity','ACHOO',72,'The sneeze happens before the subject feels it coming.','#7af7ff','#238eb5'],['Blue Screen Bug','Oddity','404',68,'Nearby electronics briefly forget what they were doing.','#5fa4ff','#254bb1'],['Chair Squeak Syndrome','Oddity','♬',62,'Every chair in the room squeaks at the same time.','#a98bff','#5941a7'],['Pocket Lint Colony','Oddity','≈',55,'Builds tiny structures from fibres and receipt fragments.','#d9c9a0','#877157'],['Bubble Brain Culture','Oddity','○',76,'Produces perfect bubbles that refuse to pop.','#77f0e8','#2f9a9c'],['Reverse Hiccup','Oddity','↺',81,'Nobody knows what a reverse hiccup is. This sample does it anyway.','#6ff2b7','#2b8d63'],
['Pixel Plague','Mutant','▦',145,'Small square lesions appear on photographs, never on skin.','#57d7ff','#214c9b'],['Gigglepox','Mutant','HA',165,'Infected test dummies somehow laugh. They have no speakers.','#ff87ba','#a32965'],['Moon Flu','Mutant','☾',172,'Activity triples under moonlight and stops near desk lamps.','#93a9ff','#373a91'],['Toast-9','Mutant','▤',155,'All bread within five metres browns slightly faster.','#f0aa5d','#8f4d1e'],['Static Rash','Mutant','⚡',188,'The vial crackles when someone nearby lies.','#6eefff','#287aa0'],['Gremlin Culture','Mutant','G',205,'Moves small tools to incorrect drawers overnight.','#9bef67','#347236'],['Wi-Fi Worm','Mutant','⌁',218,'Signal strength improves near the vial. Nobody trusts this.','#69b7ff','#234f9a'],
['Neon Nibbler','Hazard','ᗧ',470,'Tiny glowing bites appear on labels left near the sample.','#68fff2','#125f63'],['Mirror Cough','Hazard','◫',525,'Reflections cough half a second after the subject does.','#c0eaff','#4d6f88'],['Midnight Moth','Hazard','M',590,'A winged shadow circles the vial between 00:00 and 00:01.','#b896ff','#46318c'],['Floor Is Lava Variant','Hazard','▲',620,'Raises the temperature of whichever tile it is placed on.','#ff9d57','#9b3623'],['Echo Eater','Hazard','◌',680,'Removes one word from every echo in the chamber.','#82eaff','#225c73'],['Unpaid Intern Strain','Hazard','IDK',735,'Completes mysterious paperwork during unattended night shifts.','#ffe470','#8e6f24'],['Probability Rash','Hazard','%',790,'Nearby coin flips become deeply suspicious.','#8aff9c','#287c49'],
['Blackout Bloom','Black Label','✹',1550,'Every light in the lab dims when the culture flowers.','#ff5874','#611b2d'],['Doorway Fever','Black Label','▯',1740,'Subjects become convinced one specific door leads somewhere else.','#e38bff','#602486'],['Redacted Organism','Black Label','██',1980,'The original discovery notes are blank in every backup.','#ff6d70','#711d22'],['Laughing Glass','Black Label','◈',2240,'Hairline cracks form smile-shaped patterns in nearby glass.','#ffa16e','#7d3624'],['Second Shadow','Black Label','Ⅱ',2650,'Produces a second shadow under a single light source.','#a08dff','#382b77'],['Zero Patient Zero','Black Label','0²',3100,'Listed as the first sample before the project officially existed.','#f1df78','#6f5c15'],['The Quiet Jar','Black Label','…',3600,'Sound meters drop to zero within twelve centimetres.','#d4e3e3','#445458'],
['Reality Itch // Ω','Impossible','Ω',24800,'Nearby labels rewrite themselves. Nobody remembers naming it.','#e073ff','#6a20b7'],['Yesterday Culture','Impossible','-1',12800,'The timestamp on every scan is exactly one day early.','#86a7ff','#3d45a8'],['Specimen NULL','Impossible','∅',15400,'Equipment detects a full vial while cameras show it empty.','#f4f4f4','#5d5d67'],['Sunburn in a Bottle','Impossible','☀',17600,'Emits sunlight with no measurable heat or radiation source.','#ffe271','#bd5a22'],['The Last Sneeze','Impossible','✶',20100,'Audio analysis contains a voice counting down from seven.','#76fff1','#13798b'],['DO NOT SHAKE','Impossible','!',21900,'Every label simply reads DO NOT SHAKE. Nobody printed them.','#ff6b72','#8a1722'],['Inventory Ghost // Ω','Impossible','ΩΩ',26600,'The freezer inventory changes by one whenever this vial is moved.','#d879ff','#5d1ba3']
];
const specimens=seed.map((s,i)=>({id:i+1,name:s[0],rarity:s[1],glyph:s[2],base:s[3],text:s[4],liqA:s[5],liqB:s[6]}));
const racks=[
{id:'starter',name:'STARTER CULTURES',sub:'TRAINING FREEZER',price:140,level:1,a:'#205f45',b:'#12372e',glow:'#75ffad',odds:'God Rack 1:500',god:.002,weights:{Stable:54,Oddity:28,Mutant:13,Hazard:4,'Black Label':.9,Impossible:.1}},
{id:'quarantine',name:'QUARANTINE LOT',sub:'RESTRICTED STORAGE',price:340,level:2,a:'#2d6571',b:'#162c4b',glow:'#64e6ff',odds:'God Rack 1:250',god:.004,weights:{Stable:38,Oddity:30,Mutant:20,Hazard:9,'Black Label':2.6,Impossible:.4}},
{id:'blacksite',name:'BLACKSITE CASE',sub:'CLEARANCE Ω',price:820,level:4,a:'#6a2934',b:'#2d1234',glow:'#ff667d',odds:'God Rack 1:100',god:.01,weights:{Stable:18,Oddity:23,Mutant:27,Hazard:20,'Black Label':10.5,Impossible:1.5}}
];
const tools=[
{id:0,name:'Rubber Mallet',emoji:'🔨',price:0,time:1200,desc:'Slow, cheap and weirdly satisfying.'},
{id:1,name:'Bench Cracker',emoji:'🗜️',price:650,time:900,desc:'Controlled pressure. Less waiting.'},
{id:2,name:'Sonic Tapper',emoji:'🔊',price:1800,time:650,desc:'Finds the weak point with sound.'},
{id:3,name:'Laser Snapper',emoji:'⚡',price:5200,time:420,desc:'Cuts the safety collar instantly.'},
{id:4,name:'Auto-Cracker X',emoji:'🤖',price:14000,time:220,desc:'Industrial rack-opening machine.'}
];
const defaultState={credits:900,xp:0,inventory:[],discovered:[],racksOpened:0,itemsSold:0,bestPull:null,godRacks:0,market:{},returns:[],nextUID:1,tool:0};
let state=load(),currentRack=null,rackItems=[],slot=0,filter='all',ticker=12,isGod=false,holdTimer=null;
function load(){try{const raw=JSON.parse(localStorage.getItem('vialbreak-save')||'{}');return {...structuredClone(defaultState),...raw}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem('vialbreak-save',JSON.stringify(state))}
function level(){return Math.max(1,Math.floor(state.xp/500)+1)}function xpInto(){return state.xp%500}function byId(id){return specimens.find(s=>s.id===id)}function tool(){return tools[state.tool]||tools[0]}function mult(id){return state.market[id]||1}
function valueOf(item){const s=byId(item.specimenId);let v=s.base*mult(s.id);if(item.pristine)v*=1.35;if(item.grade)v*=({7:.8,8:1.08,9:1.9,10:5.2,'10P':9.2}[item.grade]||1);return Math.round(v)}
function ownedOf(id){return state.inventory.filter(i=>i.specimenId===id)}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)}
function beep(f=440,d=.06,type='sine',g=.035){try{const ac=beep.ac||(beep.ac=new(window.AudioContext||window.webkitAudioContext)()),o=ac.createOscillator(),ga=ac.createGain();o.frequency.value=f;o.type=type;ga.gain.value=g;o.connect(ga);ga.connect(ac.destination);o.start();ga.gain.exponentialRampToValueAtTime(.001,ac.currentTime+d);o.stop(ac.currentTime+d)}catch{}}
function roll(weights){let total=Object.values(weights).reduce((a,b)=>a+b,0),r=Math.random()*total;for(const[k,w]of Object.entries(weights)){r-=w;if(r<=0)return k}return'Stable'}
function boostedWeights(base){const w={...base};w.Stable*=.12;w.Oddity*=.45;w.Mutant*=1.35;w.Hazard*=2.4;w['Black Label']*=3.4;w.Impossible*=4.2;return w}
function godWeights(){return{Stable:0,Oddity:0,Mutant:10,Hazard:46,'Black Label':37,Impossible:7}}
function pull(rack,idx){let rarity=roll(isGod?godWeights():(idx===6?boostedWeights(rack.weights):rack.weights));const pool=specimens.filter(s=>s.rarity===rarity),s=pool[Math.floor(Math.random()*pool.length)];return{uid:state.nextUID++,specimenId:s.id,grade:null,pristine:Math.random()<(rank[rarity]>=4?.28:.09),serial:rank[rarity]>=5?Math.floor(1+Math.random()*999):null}}
function vialHTML(s,item=null,big=false){return `<div class="${big?'big-vial':'specimen-vial'}" style="--liqA:${s.liqA};--liqB:${s.liqB}"><div class="cap"></div><div class="glass"><div class="liquid"></div><div class="organism">${s.glyph}</div></div></div>`}
function specimenCard(s,item=null){return `<div class="specimen-card" style="--rarity:${colors[s.rarity]};--glow:${s.liqA}33">${item?.grade?`<div class="cert-stamp">CGC ${item.grade==='10P'?'10 PERFECT':item.grade}</div>`:''}<div class="spec-head"><b>${s.name.toUpperCase()}</b><span>VB-${String(s.id).padStart(3,'0')}</span></div><div class="vial-wrap">${vialHTML(s,item)}</div><div class="spec-class">${item?.pristine?'✦ PRISTINE • ':''}${s.rarity.toUpperCase()}</div><div class="spec-text">${s.text}</div><div class="spec-foot"><span>${item?.serial?`SERIAL #${String(item.serial).padStart(3,'0')}`:'FICTIONAL CULTURE'}</span><b>₡${fmt(item?valueOf(item):s.base)}</b></div></div>`}
function renderRacks(){let lv=level();$('#rackGrid').innerHTML=racks.map(r=>{let lock=lv<r.level,liqs=['#87ff6b','#68f4ee','#ffe05b','#b881ff','#ff6a79','#73a9ff','#e7e7e7'];return `<div class="rack-card ${lock?'locked':''}" style="--a:${r.a};--b:${r.b};--glow:${r.glow}"><div class="rack-top"><div><small>${r.sub}</small><h3>${r.name}</h3></div><b class="rack-price">₡ ${fmt(r.price)}</b></div><div class="rack-art"><div class="physical-rack"><div class="rack-vials">${liqs.map(c=>`<div class="tiny-vial" style="--liquid:${c}"></div>`).join('')}</div><div class="rack-label">${r.name} // 7 SEALED</div></div></div><div class="odds"><span>${r.odds}</span><span>Final Chamber boosted</span></div><button class="buy-btn" data-rack="${r.id}" ${lock?'disabled':''}>${lock?`UNLOCK AT LAB LV ${r.level}`:'BUY & CRACK RACK'}</button></div>`}).join('');$$('[data-rack]').forEach(b=>b.onclick=()=>openRack(racks.find(r=>r.id===b.dataset.rack)))}
function openRack(r){if(state.credits<r.price){toast('Not enough credits — sell duplicates on the Grey Market.');return}state.credits-=r.price;state.racksOpened++;state.xp+=40;currentRack=r;isGod=Math.random()<r.god;if(isGod)state.godRacks++;rackItems=Array.from({length:7},(_,i)=>pull(r,i));slot=0;$('#openingRackName').textContent=r.name;$('#breachBanner').classList.toggle('hidden',!isGod);renderRackVisual(r);$('#rackVisual').classList.remove('gone');$('#crackStation').classList.add('hidden');$('#revealArea').classList.remove('active');$('#nextVialBtn').classList.add('hidden');$('#finishRackBtn').classList.add('hidden');$('#openingOverlay').classList.add('active');setTimeout(()=>{$('#rackVisual').classList.add('gone');setTimeout(()=>{prepareSlot();$('#crackStation').classList.remove('hidden')},380)},isGod?1300:650);save();renderAll();if(isGod){beep(180,.18,'sawtooth',.06);setTimeout(()=>beep(120,.25,'sawtooth',.05),160)}else beep(260,.08,'triangle')}
function renderRackVisual(r){const liquids=['#80ff76','#5ce9ff','#ffdf62','#cf79ff','#ff6f78','#74a8ff','#e8ffda'];$('#rackVisual').innerHTML=liquids.map(c=>`<div class="rack-vial-big"><div class="cap"></div><div class="glass"><div class="liquid" style="--liqA:${c};--liqB:${c}88"></div></div></div>`).join('');$('#rackVisual').style.boxShadow=`0 30px 90px #000,0 0 55px ${r.glow}33 inset`}
function prepareSlot(){$('#slotNum').textContent=slot+1;$('#slotBonus').textContent=isGod?'GOD RACK':slot===6?'★ FINAL CHAMBER BOOST':'';$('#slotBonus').style.color=isGod?'#ff7486':'#ffe36e';let itm=rackItems[slot],s=byId(itm.specimenId);$('#bigVial').innerHTML=vialHTML(s,itm,true);$('#bigVial').style.filter='brightness(.32) saturate(.45)';$('#toolAnim').textContent=tool().emoji;$('#crackBtn').style.setProperty('--crackTime',tool().time+'ms');$('#crackBtn').classList.remove('hidden','loading');$('#revealArea').classList.remove('active');$('#revealArea').innerHTML='';$('#nextVialBtn').classList.add('hidden');$('#finishRackBtn').classList.add('hidden')}
$('#crackBtn').addEventListener('pointerdown',()=>{let b=$('#crackBtn');b.classList.add('loading');$('#toolAnim').classList.add('swing');holdTimer=setTimeout(()=>{b.classList.add('hidden');$('#toolAnim').classList.remove('swing');beep(140,.09,'square',.055);setTimeout(revealVial,150)},tool().time)});['pointerup','pointerleave'].forEach(e=>$('#crackBtn').addEventListener(e,()=>{clearTimeout(holdTimer);$('#crackBtn').classList.remove('loading');$('#toolAnim').classList.remove('swing')}));
function revealVial(){const item=rackItems[slot],s=byId(item.specimenId);$('#bigVial').style.filter='none';$('#crackStation').classList.add('hidden');$('#revealArea').innerHTML=`<div class="reveal-specimen ${rank[s.rarity]>=5?'big-hit':''}" style="--rarity:${colors[s.rarity]}">${specimenCard(s,item)}<div class="reveal-meta"><span>${s.rarity.toUpperCase()} ${item.pristine?'• PRISTINE':''}</span><h3>${s.name}</h3><b>INDEX VALUE &nbsp; ₡ ${fmt(valueOf(item))}</b></div></div>`;$('#revealArea').classList.add('active');if(rank[s.rarity]>=4){beep(rank[s.rarity]>=5?900:650,.18,'sine',.07);setTimeout(()=>beep(1120,.18,'sine',.04),110)}else beep(380+rank[s.rarity]*70,.07);if(slot<6)$('#nextVialBtn').classList.remove('hidden');else $('#finishRackBtn').classList.remove('hidden')}
$('#nextVialBtn').onclick=()=>{slot++;$('#revealArea').classList.remove('active');setTimeout(()=>{prepareSlot();$('#crackStation').classList.remove('hidden')},150)};$('#finishRackBtn').onclick=finishRack;$('#closeOpening').onclick=()=>{if(!$('#finishRackBtn').classList.contains('hidden'))finishRack()};
function finishRack(){for(const item of rackItems){state.inventory.push(item);if(!state.discovered.includes(item.specimenId))state.discovered.push(item.specimenId);const s=byId(item.specimenId);if(!state.bestPull||rank[s.rarity]>rank[byId(state.bestPull).rarity]||(rank[s.rarity]===rank[byId(state.bestPull).rarity]&&s.base>byId(state.bestPull).base))state.bestPull=s.id}state.xp+=rackItems.reduce((a,i)=>a+rank[byId(i.specimenId).rarity]*8,0)+(isGod?180:0);save();$('#openingOverlay').classList.remove('active');renderAll();toast(isGod?'TOTAL BREACH secured in your freezer!':'7 specimens locked into your freezer.')}
function renderCollection(){const list=specimens.filter(s=>{const o=ownedOf(s.id);if(filter==='owned')return o.length;if(filter==='graded')return o.some(i=>i.grade);if(filter==='Hazard')return rank[s.rarity]>=4;return true});$('#collectionGrid').innerHTML=list.map(s=>{const o=ownedOf(s.id);if(!state.discovered.includes(s.id))return `<div class="specimen-slot unknown"><div><b>?</b><div class="eyebrow">VB-${String(s.id).padStart(3,'0')} // UNKNOWN</div></div></div>`;const best=o.slice().sort((a,b)=>valueOf(b)-valueOf(a))[0];return `<div class="specimen-slot" data-inspect="${s.id}">${o.length?`<span class="owned-count">×${o.length}</span>`:''}${specimenCard(s,best||null)}</div>`}).join('');$$('[data-inspect]').forEach(e=>e.onclick=()=>inspect(Number(e.dataset.inspect)))}
function inspect(id){const s=byId(id),o=ownedOf(id),best=o.slice().sort((a,b)=>valueOf(b)-valueOf(a))[0];$('#inspectVial').innerHTML=specimenCard(s,best||null);$('#inspectInfo').innerHTML=`<div class="eyebrow">VB-${String(id).padStart(3,'0')} // ${s.rarity.toUpperCase()}</div><h2>${s.name}</h2><p>${s.text}</p><div class="inspect-kv"><span>Owned</span><b>${o.length}</b></div><div class="inspect-kv"><span>Raw index</span><b>₡ ${fmt(s.base*mult(s.id))}</b></div><div class="inspect-kv"><span>Best copy</span><b>${best?`₡ ${fmt(valueOf(best))}`:'—'}</b></div>`;$('#inspectModal').classList.add('active')}
$$('[data-close-inspect]').forEach(e=>e.onclick=()=>$('#inspectModal').classList.remove('active'));
function renderTools(){const t=tool();$('#currentToolDisplay').innerHTML=`<div class="emoji">${t.emoji}</div><b>${t.name}</b><small>${(t.time/1000).toFixed(2)} sec per vial</small>`;$('#toolGrid').innerHTML=tools.map((x,i)=>{const owned=i<=state.tool,current=i===state.tool;return `<div class="tool-card ${current?'current':''}"><div class="emoji">${x.emoji}</div><h3>${x.name}</h3><p>${x.desc}</p><div class="speed">CRACK TIME ${(x.time/1000).toFixed(2)}s</div><button class="upgrade-btn" data-tool="${i}" ${owned?'disabled':''}>${current?'EQUIPPED':owned?'OWNED':`UPGRADE ₡ ${fmt(x.price)}`}</button></div>`}).join('');$$('[data-tool]').forEach(b=>b.onclick=()=>buyTool(Number(b.dataset.tool)))}
function buyTool(i){const x=tools[i];if(i!==state.tool+1){toast('Upgrade tools in order.');return}if(state.credits<x.price){toast('Not enough credits for that tool.');return}state.credits-=x.price;state.tool=i;state.xp+=120;save();renderAll();toast(`${x.name} installed.`)}
function renderGradable(){const arr=state.inventory.filter(i=>!i.grade);$('#gradableList').innerHTML=arr.length?arr.slice().sort((a,b)=>valueOf(b)-valueOf(a)).map(i=>{const s=byId(i.specimenId);return `<div class="list-item"><div class="thumb" style="--liq:${s.liqA}"></div><div><b>${s.name}</b><small>${s.rarity} • ₡${fmt(valueOf(i))}</small></div><button data-grade="${i.uid}">SUBMIT</button></div>`}).join(''):'<div class="return-box"><small>No uncertified vials in freezer.</small></div>';$$('[data-grade]').forEach(b=>b.onclick=()=>submitGrade(Number(b.dataset.grade)))}
function submitGrade(uid){if(state.credits<110){toast('You need ₡110 for certification.');return}const idx=state.inventory.findIndex(i=>i.uid===uid);if(idx<0)return;const item=state.inventory.splice(idx,1)[0];state.credits-=110;state.returns.push({item,ready:Date.now()+4500});save();renderAll();toast('Vial sent to CGC. Return locker updates shortly.');setTimeout(renderAll,4700)}
function rollGrade(item){const s=byId(item.specimenId),r=Math.random()+(item.pristine?.15:0)+(rank[s.rarity]>=5?.04:0);if(r>.985)return'10P';if(r>.84)return 10;if(r>.56)return 9;if(r>.25)return 8;return 7}
function renderReturns(){const now=Date.now();$('#gradingReturns').innerHTML=state.returns.length?state.returns.map((r,i)=>{const s=byId(r.item.specimenId),ready=now>=r.ready;return `<div class="return-box ${ready?'ready':''}"><b>${ready?'SEALED RETURN READY':'CGC IS TESTING…'}</b><small>${s.name}</small>${ready?`<button data-return="${i}">REVEAL GRADE</button>`:`<small>Integrity scan in progress</small>`}</div>`}).join(''):'<div class="return-box"><small>No submissions yet.</small></div>';$$('[data-return]').forEach(b=>b.onclick=()=>claimReturn(Number(b.dataset.return)))}
function claimReturn(i){const r=state.returns[i];if(!r||Date.now()<r.ready)return;r.item.grade=rollGrade(r.item);state.inventory.push(r.item);state.returns.splice(i,1);state.xp+=80;save();renderAll();toast(`CGC ${r.item.grade==='10P'?'10 PERFECT':r.item.grade}!`);beep(r.item.grade===10||r.item.grade==='10P'?1000:700,.2,'sine',.06)}
function renderMarket(){const rows=specimens.slice().sort((a,b)=>b.base-a.base).slice(0,18);$('#marketRows').innerHTML=rows.map(s=>{let m=mult(s.id),move=(m-1)*100;return `<div class="market-row"><b>${s.name}</b><span style="color:${colors[s.rarity]}">${s.rarity}</span><span>₡${fmt(s.base*m)}</span><span class="${move>=0?'up':'down'}">${move>=0?'+':''}${move.toFixed(1)}%</span></div>`}).join('');const inv=state.inventory.slice().sort((a,b)=>valueOf(b)-valueOf(a));$('#sellList').innerHTML=inv.length?inv.map(i=>{const s=byId(i.specimenId);return `<div class="list-item"><div class="thumb" style="--liq:${s.liqA}"></div><div><b>${s.name}${i.grade?` • CGC ${i.grade}`:''}</b><small>${s.rarity}${i.pristine?' • pristine':''}</small></div><button data-sell="${i.uid}">SELL ₡${fmt(valueOf(i))}</button></div>`}).join(''):'<div class="return-box"><small>Your freezer is empty.</small></div>';$$('[data-sell]').forEach(b=>b.onclick=()=>sell(Number(b.dataset.sell)))}
function sell(uid){const idx=state.inventory.findIndex(i=>i.uid===uid);if(idx<0)return;const item=state.inventory[idx],v=valueOf(item);state.inventory.splice(idx,1);state.credits+=v;state.itemsSold++;state.xp+=12;save();renderAll();toast(`Sold for ₡${fmt(v)}.`)}
function tickMarket(){for(const s of specimens){let m=state.market[s.id]||1;m*=1+(Math.random()-.5)*.045;m=Math.max(.72,Math.min(1.42,m));state.market[s.id]=m}ticker=12;save();renderMarket()}
setInterval(()=>{ticker--;if(ticker<=0)tickMarket();$('#tickerTimer').textContent=`00:${String(Math.max(0,ticker)).padStart(2,'0')}`},1000);
function renderStats(){$('#credits').textContent=fmt(state.credits);$('#collectionCount').textContent=`${state.discovered.length} / ${specimens.length}`;$('#level').textContent=level();$('#xpLabel').textContent=`${xpInto()} / 500 XP`;$('#xpBar').style.width=`${xpInto()/5}%`;$('#racksOpened').textContent=state.racksOpened;$('#bestPull').textContent=state.bestPull?byId(state.bestPull).name:'—';$('#itemsSold').textContent=state.itemsSold;$('#godRacks').textContent=state.godRacks;$('#archivePercent').textContent=Math.round(state.discovered.length/specimens.length*100)+'%'}
function renderAll(){renderStats();renderRacks();renderCollection();renderTools();renderGradable();renderReturns();renderMarket()}
$$('.nav').forEach(n=>n.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');$$('.screen').forEach(s=>s.classList.remove('active'));$(`#screen-${n.dataset.screen}`).classList.add('active');$('#sidebar').classList.remove('open')});$$('.filter').forEach(f=>f.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));f.classList.add('active');filter=f.dataset.filter;renderCollection()});$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#resetBtn').onclick=()=>{if(confirm('Reset all VIALBREAK progress?')){localStorage.removeItem('vialbreak-save');location.reload()}};
renderAll();