const categories={
"MAKE":["a tiny movie","a cardboard invention","a paper creature","a comic strip","a fake product","a mini museum","a blanket fort","a stop-motion clip","a costume","a desk sculpture","a bookmark","a paper city"],
"COLLECT":["interesting leaves","things shaped like letters","different textures","tiny objects","cool shadows","things in one colour","household logos","interesting rocks","weird packaging","objects from each room","round things","old-looking objects"],
"PHOTO":["airplanes","reflections","shadows","something red","tiny details","cloud shapes","symmetry","objects that look like faces","a photo story","five textures","the same object 10 ways","forced-perspective scenes"],
"CREATE":["a movie idea","a new superhero","a board game","a secret code","a fake country","a theme park","a restaurant menu","a mystery story","a new sport","a comic character","an imaginary app","a game-show challenge"],
"CHALLENGE":["build the tallest paper tower","draw without lifting your pen","balance 10 objects","make something in 5 minutes","learn a simple magic trick","invent a handshake","do a no-floor obstacle course","make a domino chain","build using only 10 items","draw with your other hand","memorise 20 objects","make a one-room scavenger hunt"],
"EXPLORE":["map every room","find the oldest object at home","spot 10 things you never noticed","research a random country","watch birds from a window","identify five clouds","find north without a phone","make a backyard nature map","find objects from five countries","inspect something with a magnifier","make a sound map","find hidden patterns at home"],
"FOOD":["invent a snack plate","design a cafe menu","make a crazy toast topping","create a fruit sculpture","blind taste-test safe foods","make a fancy drink","plate a snack like a restaurant","invent a sandwich","make shaped pancakes","decorate biscuits","make a three-ingredient treat","create a snack rating contest"],
"MOVE":["make a dance routine","design an obstacle course","try a balance challenge","create a mini workout","learn a shuffle step","do a balloon keep-up challenge","invent a living-room sport","make a target toss","do an animal-walk race","create a reaction-time game","try a sock basketball challenge","make a movement dice game"],
"RANDOM":["rearrange one shelf","make a time capsule","write a letter to future you","make a weird tier list","create a quiz","make a treasure hunt","learn 10 words in a language","design your dream room","make a playlist cover","create a family awards show","make a fake newspaper","plan the perfect day"]};
const twists=["using only things already at home","in under 10 minutes","with a one-colour theme","and give it a ridiculous name","then photograph the result","with your eyes closed for the first minute","as if it came from the year 2050","in miniature","as a competition","with exactly 7 objects","without buying anything","and make a poster for it","then rate it out of 10","using recycled materials","with a mystery theme","in the funniest way possible","and hide one secret detail","in three different versions","with a friend or sibling","and make up rules for it","in silence","while pretending it is a TV challenge","with a retro theme","and tell a story about it","using only one room","with a 15-minute timer","then improve it once","and make a title card","using a random number from 1 to 20","with an unexpected ending","as professionally as you can","then make a tiny version","and document 5 steps","with a space theme","with a nature theme","with a movie-trailer vibe","with a detective theme","with a sports theme","using only paper and tape","using only 5 materials"];
const modes=["Solo","Team","Fast","Creative","Chill","Photo","Build","Learn"];
let active="ALL",rotation=0,spinning=false,last=null;
const cats=Object.keys(categories), canvas=document.querySelector('#wheel'),ctx=canvas.getContext('2d');
const palette=['#b7ff36','#ff4f91','#7b61ff','#24d7ff','#ffbe2e','#ff6659','#4be38a','#e765ff','#57a4ff'];
function draw(){const n=cats.length,r=canvas.width/2;ctx.clearRect(0,0,700,700);ctx.save();ctx.translate(r,r);ctx.rotate(rotation);cats.forEach((c,i)=>{let a=i*Math.PI*2/n-Math.PI/2,b=(i+1)*Math.PI*2/n-Math.PI/2;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r-8,a,b);ctx.closePath();ctx.fillStyle=palette[i];ctx.fill();ctx.save();ctx.rotate((a+b)/2);ctx.textAlign='right';ctx.fillStyle='#090a0f';ctx.font='bold 24px Arial';ctx.fillText(c,r-35,8);ctx.restore()});ctx.restore()}
function randomIdea(){let pool=active==='ALL'?cats:[active];let c=pool[Math.floor(Math.random()*pool.length)],base=categories[c][Math.floor(Math.random()*categories[c].length)],tw=twists[Math.floor(Math.random()*twists.length)],mode=modes[Math.floor(Math.random()*modes.length)],seed=Math.floor(Math.random()*99998)+1;return{c,idea:(base.charAt(0).toUpperCase()+base.slice(1))+" "+tw,detail:`${mode} idea #${seed.toString().padStart(5,'0')} • Try it your own way. Skip anything you don't have the stuff for.`}}
function spin(){if(spinning)return;spinning=true;let turns=5+Math.random()*5,target=rotation+turns*Math.PI*2+Math.random()*Math.PI*2,start=rotation,t0=performance.now();function anim(t){let p=Math.min(1,(t-t0)/2200),e=1-Math.pow(1-p,4);rotation=start+(target-start)*e;draw();if(p<1)requestAnimationFrame(anim);else{spinning=false;show(randomIdea())}}requestAnimationFrame(anim)}
function show(x){last=x;category.textContent=x.c;idea.textContent=x.idea;detail.textContent=x.detail;document.querySelector('#result').scrollIntoView({behavior:'smooth',block:'center'})}
function renderFilters(){filters.innerHTML='';['ALL',...cats].forEach(c=>{let b=document.createElement('button');b.className='chip'+(active===c?' on':'');b.textContent=c;b.onclick=()=>{active=c;renderFilters()};filters.appendChild(b)})}
function getSaved(){return JSON.parse(localStorage.getItem('boredSaved')||'[]')}function renderSaved(){let s=getSaved();saved.innerHTML=s.length?s.map(x=>`<div class="saveitem"><b>${x.c}</b> — ${x.idea}</div>`).join(''):'<p style="color:#777">Nothing saved yet.</p>'}
document.querySelector('#spin').onclick=spin;document.querySelector('#again').onclick=spin;document.querySelector('#save').onclick=()=>{if(!last)return;let s=getSaved();if(!s.some(x=>x.idea===last.idea))s.unshift(last);localStorage.setItem('boredSaved',JSON.stringify(s.slice(0,50)));renderSaved()};draw();renderFilters();renderSaved();